
import java.lang.*;
import javax.swing.JOptionPane;
import java.text.Normalizer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aluno
 */
public class Forca extends javax.swing.JFrame {


    String palavra, dica, letra, letraCerta;
    int erro = 0;


    public Forca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Bpalavra = new javax.swing.JButton();
        LblPalavra = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Erradas = new javax.swing.JLabel();
        LblDica = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();
        LblErradas = new javax.swing.JLabel();
        cabeca = new javax.swing.JLabel();
        corpo = new javax.swing.JLabel();
        bracoE = new javax.swing.JLabel();
        bracoD = new javax.swing.JLabel();
        pernaE = new javax.swing.JLabel();
        pernaD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Reem Kufi", 1, 48)); // NOI18N
        jLabel1.setText("JOGO DA FORCA");

        Bpalavra.setText("Escolher Palavra");
        Bpalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpalavraActionPerformed(evt);
            }
        });

        LblPalavra.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        LblPalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPalavra.setText("_");

        jButton1.setText("Escolher Letra");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Erradas.setText("Letras Erradas/Digitadas: ");

        LblDica.setText("Dica:              ");

        btReset.setText("Resetar");
        btReset.setEnabled(false);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        cabeca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cabeca.setText("O");
        cabeca.setEnabled(false);

        corpo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        corpo.setText("|");
        corpo.setEnabled(false);

        bracoE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bracoE.setText("/");
        bracoE.setEnabled(false);

        bracoD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bracoD.setText("\\");
            bracoD.setEnabled(false);

            pernaE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            pernaE.setText("/");
            pernaE.setEnabled(false);

            pernaD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            pernaD.setText("\\");
                pernaD.setEnabled(false);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Bpalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Erradas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblErradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(pernaE, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pernaD))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cabeca, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bracoE, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(corpo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(8, 8, 8)
                                        .addComponent(bracoD)))
                                .addGap(93, 93, 93))))
                    .addComponent(LblPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cabeca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bracoE)
                                    .addComponent(bracoD)
                                    .addComponent(corpo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pernaE)
                                    .addComponent(pernaD)))
                            .addComponent(jLabel1))
                        .addGap(138, 138, 138)
                        .addComponent(LblPalavra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblDica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bpalavra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReset)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Erradas, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(LblErradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                );

                pack();
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void BpalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpalavraActionPerformed
    palavra = JOptionPane.showInputDialog("Digite uma palavra: ");     
    dica = JOptionPane.showInputDialog("Digite uma dica:" );   
    Bpalavra.setEnabled(false);
    jButton1.setEnabled(true);
    btReset.setEnabled(true);
    
    //retira acento
    palavra = Normalizer.normalize(palavra, Normalizer.Form.NFD);
    palavra = palavra.replaceAll("[^\\p{ASCII}]" , "");

    //converter para maiusculo
    palavra = palavra.toUpperCase();

    //troca letra por traço
    LblPalavra.setText(palavra.replaceAll("[A-Z]", " _ "));
    
    }//GEN-LAST:event_BpalavraActionPerformed
    public void Resetar() {
       //Método que reseta as variavéis e textos
       letra = "";
       dica = "";
       palavra = "";
       letraCerta = "";
       LblErradas.setText("");
       LblDica.setText("Dica: ");
       LblPalavra.setText(" _ "); 
       erro = 0;
       Bpalavra.setEnabled(true);
       jButton1.setEnabled(false);
       btReset.setEnabled(false);
       cabeca.setEnabled(false);
       corpo.setEnabled(false);
       bracoE.setEnabled(false);
       bracoD.setEnabled(false);
       pernaE.setEnabled(false);
       pernaD.setEnabled(false);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    letra = JOptionPane.showInputDialog("Digite uma letra: ");
    //Faz a letra ficar em maiúsculo
    letra = letra.toUpperCase();
    
    //Coloca a palavra certa em seu lugar específico e se for a errada adiciona +1 no erro
    if(palavra.contains(letra)){
        letraCerta = letraCerta + letra;
        LblPalavra.setText(palavra.replaceAll("[^"+letraCerta+"]", " _ "));
    }else{
        erro++;
    }
    
    //Verifica se a uma letra já foi digitada mais de uma vez e verifica os erros
    if(LblErradas.getText().contains(letra)){
        JOptionPane.showMessageDialog(null, "Letra já digitada!");
    }else{
        LblErradas.setText(LblErradas.getText()+letra+", ");
    }
    //Verifica se ganhou ou não
    if(palavra.equals(LblPalavra.getText())){
        JOptionPane.showMessageDialog(null, "Você Ganhou!!" + "\nA palavra era: " + palavra );
        Resetar();
    }  
    
    if(erro == 2){
        LblDica.setText("Dica: "+ dica); 
    }else if(erro == 6){
        JOptionPane.showMessageDialog(null, "Você Perdeu!!" + "\nA palavra era: " + palavra);
        Resetar();
    }

    if(erro == 1){
    cabeca.setEnabled(true);
    }
    else if(erro == 2){
    corpo.setEnabled(true);
    }
    else if(erro == 3){
    bracoE.setEnabled(true);
    }
    else if(erro == 4){
    bracoD.setEnabled(true);
    }
    else if(erro == 5){
    pernaE.setEnabled(true);
    }
    else if(erro == 6){
    pernaD.setEnabled(true);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        Resetar();
    }//GEN-LAST:event_btResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bpalavra;
    private javax.swing.JLabel Erradas;
    private javax.swing.JLabel LblDica;
    private javax.swing.JLabel LblErradas;
    private javax.swing.JLabel LblPalavra;
    private javax.swing.JLabel bracoD;
    private javax.swing.JLabel bracoE;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel cabeca;
    private javax.swing.JLabel corpo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pernaD;
    private javax.swing.JLabel pernaE;
    // End of variables declaration//GEN-END:variables

}
