
import java.text.Normalizer;
import javax.swing.JOptionPane;

public class ForcaTimer extends javax.swing.JFrame {

    String palavra, dica, letra, letraCerta;
    int erro = 0, tempo = 120;
    public ForcaTimer() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Bem vindo ao Jogo da Forca!!\n"+"Após o seu amigo(a) escolher uma palavra "
        + "você terá 2 minutos para descobrir a palavra!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jLabel1 = new javax.swing.JLabel();
        cabeca = new javax.swing.JLabel();
        corpo = new javax.swing.JLabel();
        bracoE = new javax.swing.JLabel();
        bracoD = new javax.swing.JLabel();
        pernaD = new javax.swing.JLabel();
        pernaE = new javax.swing.JLabel();
        LblPalavra = new javax.swing.JLabel();
        LblDica = new javax.swing.JLabel();
        Bpalavra = new javax.swing.JButton();
        Bescolher = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        Erradas = new javax.swing.JLabel();
        LblErradas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblTempo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Reem Kufi", 1, 48)); // NOI18N
        jLabel1.setText("TIMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        cabeca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cabeca.setText("O");
        cabeca.setEnabled(false);
        getContentPane().add(cabeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 90, -1, -1));

        corpo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        corpo.setText("|");
        corpo.setEnabled(false);
        getContentPane().add(corpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 120, 16, -1));

        bracoE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bracoE.setText("/");
        bracoE.setEnabled(false);
        getContentPane().add(bracoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 15, -1));

        bracoD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bracoD.setText("\\");
            bracoD.setEnabled(false);
            getContentPane().add(bracoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 120, -1, -1));

            pernaD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            pernaD.setText("\\");
                pernaD.setEnabled(false);
                getContentPane().add(pernaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

                pernaE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                pernaE.setText("/");
                pernaE.setEnabled(false);
                getContentPane().add(pernaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 150, -1, -1));

                LblPalavra.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
                LblPalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                LblPalavra.setText("_");
                getContentPane().add(LblPalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 774, -1));

                LblDica.setText("Dica:              ");
                getContentPane().add(LblDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 764, -1));

                Bpalavra.setText("Escolher Palavra");
                Bpalavra.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BpalavraActionPerformed(evt);
                    }
                });
                getContentPane().add(Bpalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 362, -1, -1));

                Bescolher.setText("Escolher Letra");
                Bescolher.setEnabled(false);
                Bescolher.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        BescolherActionPerformed(evt);
                    }
                });
                getContentPane().add(Bescolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 391, 111, -1));

                btReset.setText("Resetar");
                btReset.setEnabled(false);
                btReset.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btResetActionPerformed(evt);
                    }
                });
                getContentPane().add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 111, -1));

                Erradas.setText("Letras Erradas/Digitadas: ");
                getContentPane().add(Erradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 469, -1, 46));
                getContentPane().add(LblErradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 469, 623, 46));

                jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                jLabel2.setText("Tempo:");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

                LblTempo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                LblTempo.setText("120 restantes...");
                getContentPane().add(LblTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

                jLabel3.setFont(new java.awt.Font("Reem Kufi", 1, 48)); // NOI18N
                jLabel3.setText("JOGO DA FORCA");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

                pack();
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void BpalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpalavraActionPerformed
        palavra = JOptionPane.showInputDialog("Digite uma palavra: ");

        dica = JOptionPane.showInputDialog("Digite uma dica:" ); 
        
        if(!dica.equals("")){ // verifica se a variavel dica está armazenando alguma coisa
            timer1.start();
        }
        Bpalavra.setEnabled(false);
        Bescolher.setEnabled(true);
        btReset.setEnabled(true);

        //retira acento
        palavra = Normalizer.normalize(palavra, Normalizer.Form.NFD);
        palavra = palavra.replaceAll("[^\\p{ASCII}]" , "");

        //converter para maiusculo
        palavra = palavra.toUpperCase();

        //troca letra por traço
        LblPalavra.setText(palavra.replaceAll("[A-Z]", " _ "));

    }//GEN-LAST:event_BpalavraActionPerformed
    public void Resetar() {
       //Método que reseta as variavéis e textos
       letra = "";
       dica = "";
       palavra = "";
       letraCerta = "";
       LblErradas.setText("");
       LblDica.setText("Dica: ");
       LblPalavra.setText(" _ "); 
       erro = 0;
       Bpalavra.setEnabled(true);
       Bescolher.setEnabled(false);
       btReset.setEnabled(false);
       cabeca.setEnabled(false);
       corpo.setEnabled(false);
       bracoE.setEnabled(false);
       bracoD.setEnabled(false);
       pernaE.setEnabled(false);
       pernaD.setEnabled(false);
       tempo = 120;
       LblTempo.setText(tempo +" Restantes...");
       timer1.stop();
    }
    private void BescolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BescolherActionPerformed
        letra = JOptionPane.showInputDialog("Digite uma letra: ");
        //Faz a letra ficar em maiúsculo
        letra = letra.toUpperCase();

        //Coloca a palavra certa em seu lugar específico e se for a errada adiciona +1 no erro
        if(palavra.contains(letra)){
            letraCerta = letraCerta + letra;
            LblPalavra.setText(palavra.replaceAll("[^"+letraCerta+"]", " _ "));
        }else{
            erro++;
        }

        //Verifica se a uma letra já foi digitada mais de uma vez e verifica os erros
        if(LblErradas.getText().contains(letra)){
            JOptionPane.showMessageDialog(null, "Letra já digitada!");
        }else{
            LblErradas.setText(LblErradas.getText()+letra+", ");
        }
        //Verifica se ganhou ou não
        if(palavra.equals(LblPalavra.getText())){
            JOptionPane.showMessageDialog(null, "Você Ganhou!!" + "\nA palavra era: " + palavra );
            Resetar();
        }

        if(erro == 2){
            LblDica.setText("Dica: "+ dica);
        }else if(erro == 6){
            JOptionPane.showMessageDialog(null, "Você Perdeu!!" + "\nA palavra era: " + palavra);
            Resetar();
        }

        switch (erro) {
            case 1:
                cabeca.setEnabled(true);
                break;
            case 2:
                corpo.setEnabled(true);
                break;
            case 3:
                bracoE.setEnabled(true);
                break;
            case 4:
                bracoD.setEnabled(true);
                break;
            case 5:
                pernaE.setEnabled(true);
                break;
            case 6:
                pernaD.setEnabled(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_BescolherActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        Resetar();
    }//GEN-LAST:event_btResetActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        tempo--; //faz o tempo diminuir continuamente
        LblTempo.setText(String.valueOf(tempo) + " Restantes...");
        if(tempo == 0){
        JOptionPane.showMessageDialog(null,"Você Perdeu! O Tempo Acabou!");
           timer1.stop(); // para o timer
        }        
    }//GEN-LAST:event_timer1OnTime

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForcaTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForcaTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForcaTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForcaTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForcaTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bescolher;
    private javax.swing.JButton Bpalavra;
    private javax.swing.JLabel Erradas;
    private javax.swing.JLabel LblDica;
    private javax.swing.JLabel LblErradas;
    private javax.swing.JLabel LblPalavra;
    private javax.swing.JLabel LblTempo;
    private javax.swing.JLabel bracoD;
    private javax.swing.JLabel bracoE;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel cabeca;
    private javax.swing.JLabel corpo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pernaD;
    private javax.swing.JLabel pernaE;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
