
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aluno
 */
public class JododaVelha extends javax.swing.JFrame {

    /**
     * Creates new form JododaVelha
     */
    int jogador = 1, CntP1 = 0, CntP2 = 0, P1V = 0, P2V = 0;

    public JododaVelha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblJogador = new javax.swing.JLabel();
        JG1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JG2 = new javax.swing.JLabel();
        Btn9 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Linhas = new javax.swing.JLabel();
        BtnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblJogador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblJogador.setText("JOGADOR 1 (X) FAÇA SUA JOGADA!");
        LblJogador.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LblJogadorComponentHidden(evt);
            }
        });
        getContentPane().add(LblJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 310, 30));

        JG1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JG1.setText("0");
        getContentPane().add(JG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 10, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("PLACAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("JOGADOR 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        JG2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JG2.setText("0");
        getContentPane().add(JG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        Btn9.setBackground(new java.awt.Color(220, 220, 220));
        Btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 100, 100));

        Btn1.setBackground(new java.awt.Color(220, 220, 220));
        Btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 100));

        Btn2.setBackground(new java.awt.Color(220, 220, 220));
        Btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 100, 100));

        Btn3.setBackground(new java.awt.Color(220, 220, 220));
        Btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 100, 100));

        Btn6.setBackground(new java.awt.Color(220, 220, 220));
        Btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, 100));

        Btn5.setBackground(new java.awt.Color(220, 220, 220));
        Btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, 100));

        Btn4.setBackground(new java.awt.Color(220, 220, 220));
        Btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 100));

        Btn7.setBackground(new java.awt.Color(220, 220, 220));
        Btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 100));

        Btn8.setBackground(new java.awt.Color(220, 220, 220));
        Btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 100, 100));

        Linhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Velha.png"))); // NOI18N
        getContentPane().add(Linhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BtnReset.setText("Resetar");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(BtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 80, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("JOGADOR 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        jogada(Btn9);
        vencedor(Btn9.getText()); 
        empate();
    }//GEN-LAST:event_Btn9ActionPerformed
    
    public void jogada(javax.swing.JButton BTN){
        if(jogador == 1){
            BTN.setText("X");
            jogador = 0;
            CntP1++;
            BTN.setEnabled(false);
            LblJogador.setText("JOGADOR 2 (O) FAÇA SUA JOGADA!");  
        }else{
            BTN.setText("O");
            jogador = 1;
            CntP2++;
            BTN.setEnabled(false);
            LblJogador.setText("JOGADOR 1 (X) FAÇA SUA JOGADA!");
        }
    }
    
    public void mostrarP1(){
        JOptionPane.showMessageDialog(null,"Jogador 1 é o Vencedor!!");
        P1V++;
        resetar();
        JG1.setText(String.valueOf(P1V));
    }
    
    public void mostrarP2(){
        JOptionPane.showMessageDialog(null,"Jogador 2 é o Vencedor!!");
        P2V++;
        resetar();
        JG2.setText(String.valueOf(P2V));
    }

    public void vencedor(String v){
        if(Btn1.getText().equals(v) && Btn2.getText().equals(v) && Btn3.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn4.getText().equals(v) && Btn5.getText().equals(v) && Btn6.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn7.getText().equals(v) && Btn8.getText().equals(v) && Btn9.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn1.getText().equals(v) && Btn4.getText().equals(v) && Btn7.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn1.getText().equals(v) && Btn5.getText().equals(v) && Btn9.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn2.getText().equals(v) && Btn5.getText().equals(v) && Btn8.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn3.getText().equals(v) && Btn6.getText().equals(v) && Btn9.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }else if(Btn3.getText().equals(v) && Btn5.getText().equals(v) && Btn7.getText().equals(v)){
            if(jogador == 0){
                mostrarP1();
            }else{
                mostrarP2();
            }
        }
    }
    

    public void empate(){ 
       if(CntP1 == 5){
            JOptionPane.showMessageDialog(null, "Jogo Empatado!!");
            resetar();
       }
    }
    
    public void resetar(){
        jogador = 1;
        CntP1 = 0;
        CntP2 = 0;
        Btn1.setEnabled(true);
        Btn2.setEnabled(true);
        Btn3.setEnabled(true);
        Btn4.setEnabled(true);
        Btn5.setEnabled(true);
        Btn6.setEnabled(true);
        Btn7.setEnabled(true);
        Btn8.setEnabled(true);
        Btn9.setEnabled(true);
        LblJogador.setText("JOGADOR 1 (X) FAÇA SUA JOGADA!");
        Btn1.setText("");
        Btn2.setText("");
        Btn3.setText("");
        Btn4.setText("");
        Btn5.setText("");
        Btn6.setText("");
        Btn7.setText("");
        Btn8.setText("");
        Btn9.setText("");
    }

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        jogada(Btn1);   
        vencedor(Btn1.getText());
        empate();
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        jogada(Btn2);
        vencedor(Btn2.getText());
        empate();
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        jogada(Btn3);
        vencedor(Btn3.getText());
        empate();
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        jogada(Btn6);
        vencedor(Btn6.getText()); 
        empate();
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        jogada(Btn5);
        vencedor(Btn5.getText()); 
        empate();
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        jogada(Btn4);
        vencedor(Btn4.getText()); 
        empate();
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        jogada(Btn7);
        vencedor(Btn7.getText()); 
        empate();
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        jogada(Btn8);
        vencedor(Btn8.getText()); 
        empate();
    }//GEN-LAST:event_Btn8ActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        resetar();
        JG1.setText("0");
        JG2.setText("0");
        P1V = 0;
        P2V = 0;
    }//GEN-LAST:event_BtnResetActionPerformed

    private void LblJogadorComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LblJogadorComponentHidden

    }//GEN-LAST:event_LblJogadorComponentHidden

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JododaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JododaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JododaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JododaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JododaVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnReset;
    private javax.swing.JLabel JG1;
    private javax.swing.JLabel JG2;
    private javax.swing.JLabel LblJogador;
    private javax.swing.JLabel Linhas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private String ValueOf(int CntP1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Object jogada(String x) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}