/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aluno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblImage = new javax.swing.JLabel();
        Lbl1 = new javax.swing.JLabel();
        Lbl3 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MGeral = new javax.swing.JMenu();
        MJogosPalavra = new javax.swing.JMenu();
        JogodaForca = new javax.swing.JMenuItem();
        JogoForcaTimer = new javax.swing.JMenuItem();
        MJogosCoop = new javax.swing.JMenu();
        JogodaVelha = new javax.swing.JMenuItem();
        MJogoReciclagem = new javax.swing.JMenu();
        JogodaReciclagem1 = new javax.swing.JMenuItem();
        MJogosQuiz = new javax.swing.JMenu();
        JogoQuiz = new javax.swing.JMenuItem();
        MSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mamaco.png"))); // NOI18N

        Lbl1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Lbl1.setText("Bem vindo ao Laucher");

        Lbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lbl3.setText("Escolha um jogo na NavBar");

        MGeral.setText("Jogos");

        MJogosPalavra.setText("Jogos de Palavras");

        JogodaForca.setText("Jogo da Forca");
        JogodaForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogodaForcaActionPerformed(evt);
            }
        });
        MJogosPalavra.add(JogodaForca);

        JogoForcaTimer.setText("Jogo da Forca Timer");
        JogoForcaTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogoForcaTimerActionPerformed(evt);
            }
        });
        MJogosPalavra.add(JogoForcaTimer);

        MGeral.add(MJogosPalavra);

        MJogosCoop.setText("Jogos Coop");

        JogodaVelha.setText("Jogo da Velha");
        JogodaVelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogodaVelhaActionPerformed(evt);
            }
        });
        MJogosCoop.add(JogodaVelha);

        MGeral.add(MJogosCoop);

        MJogoReciclagem.setText("Jogos de Recicla");
        MJogoReciclagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MJogoReciclagemMouseClicked(evt);
            }
        });

        JogodaReciclagem1.setText("Jogo Reciclagem");
        JogodaReciclagem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JogodaReciclagem1MouseClicked(evt);
            }
        });
        JogodaReciclagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogodaReciclagem1ActionPerformed(evt);
            }
        });
        MJogoReciclagem.add(JogodaReciclagem1);

        MGeral.add(MJogoReciclagem);

        MJogosQuiz.setText("Jogos Quiz");

        JogoQuiz.setText("Jogo Quiz");
        JogoQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogoQuizActionPerformed(evt);
            }
        });
        MJogosQuiz.add(JogoQuiz);

        MGeral.add(MJogosQuiz);

        MenuBar.add(MGeral);

        MSobre.setText("Sobre");
        MenuBar.add(MSobre);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LblImage)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Lbl3)
                        .addGap(36, 36, 36))
                    .addComponent(Lbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LblImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(Lbl1)
                        .addGap(44, 44, 44)
                        .addComponent(Lbl3)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MJogoReciclagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MJogoReciclagemMouseClicked

    }//GEN-LAST:event_MJogoReciclagemMouseClicked

    private void JogodaForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogodaForcaActionPerformed
        Forca ff = new Forca();
        ff.setVisible(true);
    }//GEN-LAST:event_JogodaForcaActionPerformed

    private void JogodaVelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogodaVelhaActionPerformed
        JododaVelha jv = new JododaVelha();
        jv.setVisible(true);
    }//GEN-LAST:event_JogodaVelhaActionPerformed

    private void JogoForcaTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogoForcaTimerActionPerformed
        ForcaTimer fft = new ForcaTimer();
        fft.setVisible(true);
    }//GEN-LAST:event_JogoForcaTimerActionPerformed

    private void JogodaReciclagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogodaReciclagem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JogodaReciclagem1ActionPerformed

    private void JogodaReciclagem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JogodaReciclagem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JogodaReciclagem1MouseClicked

    private void JogoQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogoQuizActionPerformed
        Quiz q = new Quiz();
        q.setVisible(true);
    }//GEN-LAST:event_JogoQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JogoForcaTimer;
    private javax.swing.JMenuItem JogoQuiz;
    private javax.swing.JMenuItem JogodaForca;
    private javax.swing.JMenuItem JogodaReciclagem1;
    private javax.swing.JMenuItem JogodaVelha;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel LblImage;
    private javax.swing.JMenu MGeral;
    private javax.swing.JMenu MJogoReciclagem;
    private javax.swing.JMenu MJogosCoop;
    private javax.swing.JMenu MJogosPalavra;
    private javax.swing.JMenu MJogosQuiz;
    private javax.swing.JMenu MSobre;
    private javax.swing.JMenuBar MenuBar;
    // End of variables declaration//GEN-END:variables
}
